### ISSUE TITLE
Add balance to account

### ISSUE THREAD

**Issue by mmiikkkkaa** [holixon/cqrs-meets-hexagonal#18]
*As* bank accound provider
*I want* bank accounts to have a balance
*so* customers can transfer money

Hints: 
- use a domain object "money" as balance type (wrapping a BigDecimal)
- don't care about currency for now

**Comment by rafaelcp94** [comment]
Pull Request: https://github.com/holixon/cqrs-meets-hexagonal/pull/27/files
